apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-5c95ec56-62a7-4735-a231-5b55acb62363
  name: devfile-sample
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample
status:
  loadBalancer: {}
